# Generated by Django 5.2.6 on 2025-10-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_product_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
