# Generated by Django 5.2.6 on 2025-10-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
