# Generated by Django 5.2.6 on 2025-10-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_alter_product_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.AddField(
            model_name='product',
            name='spl_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core_app.supplier'),
            preserve_default=False,
        ),
    ]
