# Generated by Django 5.2.6 on 2025-10-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_product_supplier_product_spl_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='spl_id',
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
