# Generated by Django 6.0 on 2026-01-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_remove_product_spl_id_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_Img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_Img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
